spring:
  profiles:
    active: local_h2

---
spring:
  config:
    activate:
      on-profile: local_h2
  datasource:
    url: jdbc:h2:tcp://localhost/~/honey-shop-test
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

cloud:
  aws:
    s3:
      bucket: ${CLOUD_AWS_S3_BUCKET}
    credentials:
      access-key: ${CLOUD_AWS_CREDENTIALS_ACCESS-KEY}
      secret-key: ${CLOUD_AWS_CREDENTIALS_SECRET-KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

cloud:
  aws:
    s3:
      bucket: ${CLOUD_AWS_S3_BUCKET}
    credentials:
      access-key: ${CLOUD_AWS_CREDENTIALS_ACCESS-KEY}
      secret-key: ${CLOUD_AWS_CREDENTIALS_SECRET-KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false